[Refactoring] 이미지 업로드 class화
wecode-bootcamp-korea/27-2nd-AirPnP-backend pull request #13
Opened 2021-12-22 08:16 UTC by jumyeong33

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 이미지 업로더를 클래스화 시켜서 core app으로 이동

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 사진 한장 올리는 method 및 여러장 올리는 method 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 클래스화시키는 이유와 요령을 터득했습니다.

<br />

## :: 기타 질문 및 특이 사항

2021-12-22 08:26 UTC, lordmyshepherd requested changes

2021-12-22 08:26 UTC, lordmyshepherd commented on users/views.py
> +            )
이부분은 클래스 밖에 선언하셔야 합니다!

2021-12-22 10:42 UTC, jumyeong33 commented on users/views.py
> +            )
수정했습니다.

2021-12-23 07:38 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-23 07:38 UTC, merged