[Create] Social_login
wecode-bootcamp-korea/27-2nd-AirPnP-backend pull request #3
Opened 2021-12-15 06:59 UTC by ghimlilo

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 소셜 로그인 api를 활용한 로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

- 카카오에서 request로 받은 json메세지 활용하여 에러처리
- 카카오 서버로 사용자 정보 요청하여 자체 서비스를 위한 토큰 발급ㅂ

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-12-15 07:17 UTC, lordmyshepherd commented
PR 하나에 하나의 기능만 올라올 수 있도록 수정해주세요~
지금은 login, logout 두개의 기능이 올라와 있습니다!

2021-12-15 07:52 UTC, lordmyshepherd requested changes

2021-12-15 07:52 UTC, lordmyshepherd commented on users/views.py
> +            result        = requests.get(url, headers = headers)
`requests` 모듈을 사용하실 때에는 `timeout` 옵션을 반드시 설정해주셔야 합니다.
그 이유는 timeout option을 추가하지 않으면 서버의 응답을 계속해서 기다리고 있는 문제가 발생 합니다. timeout 옵션을 추가해 주세요.

```python
예를 들어
class KakaoLoginView(View):
    def post(self, request):
        try:
            kakao_access_token    = request.headers['Authorization']
            kakao_user_api_url    = '<https://kapi.kakao.com/v2/user/me>'
            headers     = {"Authorization": f"Bearer ${kakao_access_token}"}

            response = requests.get(kakao_user_api_url, headers = headers, timeout = ..)

```

2021-12-15 07:52 UTC, lordmyshepherd commented on users/views.py
> +class SignInView(View):
아래와 같이 Kakao API 관련된 로직은 class로 그룹핑할 수 있습니다.  

그렇게 되면 kakao API 관련된 로직은 하나의 class에서 관리하면 된다는 장점이 있고, 만약에 나중에 kakao api 호출부의 수정일 있을 경우 `KakaoLoginView`를 수정할 필요가 없이 `KakaoAPI` 클래스만 수정하면 됩니다. 

결국 Kakao API를 호출하는 위치에서는 Interface만 알고 사용하면 되고 내부적으로 어떻게 구현되었는지 알 필요가 없습니다.

```python
# kakao.py

class KakaoAPI:
    def __init__(self, access_token):
        self.access_token = access_token
        self.user_url     = 'https://kapi.kakao.com/v2/user/me'
				self.map_url      = 

    def get_kakao_user(self):
        headers = {"Authorization": f"Bearer ${self.access_token}"}

        response = requests.get(self.user_url, headers=headers)
    
	if not response.status_code == 200:
	    return
	
	return response.json()

    def get_location():
        return   

class KakaoLoginView(View):
    def post(self, request):
        try:
            kakao_access_token = request.headers['Authorization']
            kakao_user = KakaoAPI(kakao_access_token)

```

2021-12-15 12:28 UTC, ghimlilo commented on users/views.py
> +            result        = requests.get(url, headers = headers)
수정하였습니다!

2021-12-15 12:28 UTC, ghimlilo commented on users/views.py
> +class SignInView(View):
수정하였습니다!

2021-12-16 02:14 UTC, lordmyshepherd requested changes

2021-12-16 02:14 UTC, lordmyshepherd commented on core/models.py
> +# from django.db import models
주석처리가 되어 있네요? 확인 부탁드립니다.

2021-12-16 02:14 UTC, lordmyshepherd commented on users/urls.py
> +
빈 줄은 지워주세요! 마지막에 push 하시고 file change 누르셔서 최종적으로 확인 부탁드립니다!
디테일에 신경 써주세요!
```suggestion
```

2021-12-16 02:14 UTC, lordmyshepherd commented on core/utils/KakaoAPI.py
> +from django.http                import JsonResponse
```suggestion
from django.http import JsonResponse
```

2021-12-16 02:14 UTC, lordmyshepherd commented on users/views.py
> +
빈 줄은 지워주세요!

2021-12-16 02:14 UTC, lordmyshepherd commented on users/views.py
> +    def post(self, request):
로직은 아주 깔끔합니다 👍🏻

2021-12-16 02:17 UTC, lordmyshepherd commented
위에서 드린 피드백과 유닛테스트 추가해서 다시 올려주세요~

2021-12-16 13:47 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2021-12-16 13:47 UTC, merged