[Add] : BookingView 예약기능 구현
wecode-bootcamp-korea/27-2nd-AirPnP-backend pull request #5
Opened 2021-12-15 07:18 UTC by jumyeong33

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 호스트 상세페이지에서 예약하기 기능 구현
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 오늘 날짜보다 예약날이 뒤에 있다면 에러 403
2. 예약 끝나는 날짜가 예약 시작 날보다 앞에 있다면 에러 403 
3. 예약 하려는 호스트가 해당날짜에 예약이 되어있으면 에러 403 반환
4. 예약 성공시 booking_number 반환 200 성공

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- datetime에 대해 공부할 시간이 되었습니다. 또한 범위 비교에 대해 생각해볼수 있었따.

<br />

## :: 기타 질문 및 특이 사항

2021-12-16 02:25 UTC, lordmyshepherd requested changes

2021-12-16 02:25 UTC, lordmyshepherd commented on bookings/views.py
> +
여기는 왜 return문과 if문 사이에 한 칸 띄워져 있는 건가요?
```suggestion
```

2021-12-16 02:25 UTC, lordmyshepherd commented on bookings/views.py
> +        return JsonResponse({"예약 성공 " : booking.booking_number}, status= 200)
key값에 문제가 있어 보이지 않나요?
```suggestion
        return JsonResponse({"예약 성공 " : booking.booking_number}, status= 200)
```

2021-12-16 02:39 UTC, jumyeong33 commented on bookings/views.py
> +
필요 없는 공백 입니다

2021-12-16 02:39 UTC, jumyeong33 commented on bookings/views.py
> +        return JsonResponse({"예약 성공 " : booking.booking_number}, status= 200)
공백 제거하겠습니다;;

2021-12-16 06:27 UTC, lordmyshepherd commented
유닛 테스트만 작성해서 올려주세요~

2021-12-20 02:07 UTC, jamessoun93 commented
유닛테스트 작성해서 올려주세요!

2021-12-20 08:13 UTC, merged