[Create] HostView/test.py
wecode-bootcamp-korea/27-2nd-AirPnP-backend pull request #9
Opened 2021-12-17 08:43 UTC by ghimlilo

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 호스트 등록 페이지 구현 및 테스트 파일 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
[호스트 등록 기능 구현]
 - signin_decorator를 통해 발급받은 token으로 인가받은 사용자만 호스트로 등록이 가능
 - 한 명의 user가 여러 호스트로 등록 할 수 있으나, 같은 카테고리로 등록하는 경우에는 data를 생성하지 않음
 - 호스트 등록시에 주소를 입력하면 longitude, latitude로 변환하여 저장하여 > 위치 기반 host 검색시 활용하고자 함

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

 - 이미 host로 등록한 user의 category를 가져와 해당 user가 host로 새롭게 등록시에 전달한 category를 비교하여 host등록 여부를 판단하는 과정(get_or_create가 쉽지 않았음
 
 - test 파일 작성시에 input data를 작성할 때 여러 에러와 실수를 발견함
  1) raise self.model.DoesNotExist(
  categories.models.Category.DoesNotExist: Category matching query does not exist. 
   : setUp, input data 작성시 컬럼명 지정 오류 

 2) AssertionError: {'message': 'INVALID_TOKEN'} != {'message': 'Registered Category'}
    - {'message': 'INVALID_TOKEN'}
    + {'message': 'Registered Category'}
   : decorator를 사용하는 기능의 경우, setUP data에 등록한 user id로 token을 발급해서 test 해야 함

3) AssertionError: {'result': 'Resisterd Category'} != {'message': 'Registered Category'}
    - {'result': 'Resisterd Category'}
    ?   ^  ^^^      ^
    + {'message': 'Registered Category'}
    ?   ^  ^^^^      ^     +
     : test 하는 view와 test 파일의 해당 내용을 다르게 작성
4) success와 fail test시에, input data를 잘못 기입하여(이미 등록된 category로 test 하여 success가 안됨) 오류

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2021-12-17 10:38 UTC, lordmyshepherd requested changes

2021-12-17 10:38 UTC, lordmyshepherd commented on users/views.py
> +            hosts    = Host.objects.filter(user=user)
line 54 코드는 어디서 사용되는 건가요?

2021-12-17 10:38 UTC, lordmyshepherd commented on users/views.py
> +            users    = location.geocode(address)
users라는 변수에 담긴 정보가 사용자 정보인가요?
위치 정보 아닌가요?

2021-12-17 10:38 UTC, lordmyshepherd commented on users/views.py
> +            location = Nominatim(user_agent="Users")
Nominatim를 사용하신 이유가 뭔가요?

2021-12-17 11:32 UTC, ghimlilo commented on users/views.py
> +            location = Nominatim(user_agent="Users")
사용자로부터 주소를 입력 받아  위도와 경도만을 뽑아 front-end로 다시 전달하기 위해서 python geolocation document를 참고하여 Nominatim API의 geocoder를 사용, 주소로 부터 latitude, longitude를 얻었습니다!

2021-12-17 12:00 UTC, ghimlilo commented on users/views.py
> +            users    = location.geocode(address)
네 위치정보 입니다. 사용자 위치를 의믜하는 변수명으로 수정하겠습니다! (사용하는 app 이름과 같은 변수명을 사용해야 하는 것으로 잘못 알았습니다.)

2021-12-17 12:00 UTC, ghimlilo commented on users/views.py
> +            hosts    = Host.objects.filter(user=user)
삭제하겠습니다!

2021-12-18 01:09 UTC, lordmyshepherd requested changes

2021-12-18 01:09 UTC, lordmyshepherd commented on users/views.py
> +            hosts.save()
마지막 수정사항이 될 것 같습니다.
`get_or_create` 함수는 데이터를 생성하거나 존재하는 경우 불러와서 다음 작업을 이어나갈 때 사용하는 로직입니다.

지금 로직은 생성되지 않은 경우 중복으로 판단해서 400 에러를 반환해주고 있습니다.
중복 체크가 목적이라면 get_or_create() 함수 보다는 `exists()` method로 중복을 검증하고 이후에 등록하는 로직이 이해하기 쉽습니다.

2021-12-18 08:43 UTC, ghimlilo commented on users/views.py
> +            hosts.save()
수정하였습니다!

2021-12-20 04:16 UTC, ghimlilo commented
conflicts 해결하였습니다!

2021-12-20 08:29 UTC, merged